---
kind: pipeline
type: docker
name: k3s-root-linux

platform:
  os: linux
  arch: amd64

steps:
- name: build-amd64
  image: rancher/dapper:v0.5.0
  resources:
    cpu: 12000
    memory: 8Gi
  commands:
  - dapper ci
  environment:
    BUILDARCH: amd64
    VERBOSE: "0"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: fossa-amd64
  depends_on:
    - build-amd64
  image: registry.suse.com/suse/sle15:15.6
  failure: ignore
  environment:
    FOSSA_API_KEY:
      from_secret: FOSSA_API_KEY
  commands:
    - zypper -n install curl unzip
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | sh"
    - fossa analyze
    - fossa test
  when:
    instance:
      - drone-publish.k3s.io
    ref:
      include:
        - "refs/heads/master"
    event:
      - push
      - tag

- name: github-amd64-binary-release
  depends_on:
    - fossa-amd64
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - dist/k3s-*amd64.tar
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: build-riscv64
  image: rancher/dapper:v0.5.0
  resources:
    cpu: 12000
    memory: 8Gi
  commands:
  - dapper ci
  environment:
    BUILDARCH: riscv64
    VERBOSE: "0"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github-riscv64-binary-release
  depends_on:
    - build-riscv64
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-riscv64.txt
    checksum_flatten: true
    files:
    - dist/k3s-*riscv64.tar
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: k3s-root-linux-arm

platform:
  os: linux
  arch: arm64

steps:
- name: build-arm64
  image: rancher/dapper:v0.5.0
  commands:
  - dapper ci
  environment:
    BUILDARCH: arm64
    VERBOSE: "0"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github-arm64-binary-release
  depends_on:
    - build-arm64
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - dist/k3s-*arm64.tar
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

- name: build-arm
  image: rancher/dapper:v0.5.0
  commands:
  - dapper ci
  environment:
    BUILDARCH: arm
    VERBOSE: "0"
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github-arm-binary-release
  depends_on:
    - build-arm
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - dist/k3s-*arm.tar
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.k3s.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock