FROM ubuntu:18.04 AS ubuntu
RUN yes | unminimize

# setup prereqs
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    ccache \
    gcc \
    git \
    g++ \
    rsync \
    bc \
    wget \
    curl \
    ca-certificates \
    ncurses-dev \
    python \
    unzip

ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT ./artifacts ./dist
ENV DAPPER_ENV BUILDARCH
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]