#!/bin/bash

pushd /usr/src/buildroot

cp -rfv /source/package/* package/
cp /source/buildroot/config /usr/src/buildroot/.config
cp /source/buildroot/${BUILDARCH}config /usr/src/buildroot/.config-arch
cat .config-arch >> .config

make -s oldconfig
make -s

popd
