#!/usr/bin/env bash

set -eux

pushd /usr/src/buildroot

cp -rf /source/package/* package/
cp /source/buildroot/config /usr/src/buildroot/.config
cp "/source/buildroot/${BUILDARCH}config" /usr/src/buildroot/.config-arch
cat .config-arch >> .config

V="${VERBOSE:=0}"

unset VERBOSE

make -s V="${V}" oldconfig
make -s V="${V}" toolchain
make -s V="${V}" world

popd
