#!/usr/bin/env bash

set -eux -o pipefail

: "${BUILDROOT_VERSION:=2021.02.7}"
export BUILDROOT_VERSION

mkdir -p /usr/src/buildroot

curl -fL https://github.com/buildroot/buildroot/archive/refs/tags/${BUILDROOT_VERSION}.tar.gz | tar xz -C /usr/src/buildroot --strip-components=1
