#!/bin/bash

set -ex

export BUILDROOT_VERSION=2020.11.1

mkdir -p /usr/src/buildroot

curl -fL https://buildroot.org/downloads/buildroot-${BUILDROOT_VERSION}.tar.bz2 | tar xvjf - -C /usr/src/buildroot --strip-components=1
