#!/bin/bash

mkdir -p /source/artifacts/${BUILDARCH}/bin /source/artifacts/${BUILDARCH}/xtables-bin /source/artifacts/${BUILDARCH}/etc /source/dist

pushd /usr/src

# copy binaries
cp -d buildroot/output/target/usr/sbin/*tables* /source/artifacts/${BUILDARCH}/bin/
cp buildroot/output/target/usr/sbin/conntrack /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/sbin/ethtool /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/sbin/ipset /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/bin/find /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/bin/nsenter /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/bin/pigz /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/bin/socat /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/bin/coreutils /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/sbin/ip /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/sbin/blkid /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/sbin/losetup /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/bin/busybox /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/sbin/swanctl /source/artifacts/${BUILDARCH}/bin/ 
cp buildroot/output/target/usr/libexec/ipsec/charon /source/artifacts/${BUILDARCH}/bin/

# download pre-built binaries
SLIRP4NETNS_VERSION="v1.1.8"
FUSE_OVERLAYFS_VERSION="v1.3.0"
uname_m="${BUILDARCH}"
case "${BUILDARCH}" in
    "amd64")
        uname_m="x86_64" ;;
    "arm64")
        uname_m="aarch64" ;;
    "arm")
        uname_m="armv7l" ;;
esac
curl -o /source/artifacts/${BUILDARCH}/bin/slirp4netns -sSL https://github.com/rootless-containers/slirp4netns/releases/download/${SLIRP4NETNS_VERSION}/slirp4netns-${uname_m}
chmod +x /source/artifacts/${BUILDARCH}/bin/slirp4netns
curl -o /source/artifacts/${BUILDARCH}/bin/fuse-overlayfs -sSL https://github.com/containers/fuse-overlayfs/releases/download/${FUSE_OVERLAYFS_VERSION}/fuse-overlayfs-${uname_m}
chmod +x /source/artifacts/${BUILDARCH}/bin/fuse-overlayfs

# save etc
cp -rp buildroot/output/target/var/lib/rancher/k3s/agent/* /source/artifacts/${BUILDARCH}/etc/

cp -r /source/iptables-detect/*.sh /source/artifacts/${BUILDARCH}/xtables-bin/

# setup links
link() { \
    for l in $(find -L buildroot/output/target/ -samefile buildroot/output/target/$1/$2 | xargs -n 1 basename | sort -u | grep -v "^$2\$"); do \
        ln -s $2 /source/artifacts/${BUILDARCH}/bin/$l; \
    done; \
};

link bin busybox;
link usr/bin coreutils;
ln -sf pigz /source/artifacts/${BUILDARCH}/bin/unpigz;
mkdir -p /source/artifacts/${BUILDARCH}/bin/aux;
rm -f /source/artifacts/${BUILDARCH}/bin/mount;
rm -f /source/artifacts/${BUILDARCH}/bin/modprobe;
ln -sf ../busybox /source/artifacts/${BUILDARCH}/bin/aux/mount;
ln -sf ../busybox /source/artifacts/${BUILDARCH}/bin/aux/modprobe;
mv /source/artifacts/${BUILDARCH}/bin/*tables* /source/artifacts/${BUILDARCH}/xtables-bin/;
for target in iptables iptables-save iptables-restore ip6tables ip6tables-save ip6tables-restore; do
    ln -sf iptables-detect.sh /source/artifacts/${BUILDARCH}/xtables-bin/$target;
done;
cp -rp /source/artifacts/${BUILDARCH}/xtables-bin/* /source/artifacts/${BUILDARCH}/bin/aux;

tar cf - -C /source/artifacts/${BUILDARCH} ./bin ./etc > /source/dist/k3s-root-${BUILDARCH}.tar
tar cf - -C /source/artifacts/${BUILDARCH} --transform s/xtables-bin/bin/ ./xtables-bin > /source/dist/k3s-root-xtables-${BUILDARCH}.tar
popd
