#!/usr/bin/env bash

set -eux

shopt -s nullglob
SOURCE="$(realpath $(dirname "$0")/..)"

rsync -amv ${SOURCE}/package/ /usr/src/buildroot/package/

pushd /usr/src/buildroot
for PATCH in ${SOURCE}/patches/*.patch; do
  patch -t -p1 -i "${PATCH}"
done
popd

cat ${SOURCE}/buildroot/{"${BUILDARCH}config",config} > /usr/src/buildroot/.config
